// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard";
  };
  "routes/Welcome.tsx": {
    id: "routes/Welcome";
    page: "/";
  };
  "routes/Dashboard.tsx": {
    id: "routes/Dashboard";
    page: "/dashboard";
  };
};