// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/receiver": {
    params: {};
  };
  "/gifter": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/choicerg": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/receiver" | "/gifter" | "/dashboard" | "/choicerg";
  };
  "routes/Welcome.tsx": {
    id: "routes/Welcome";
    page: "/";
  };
  "routes/DB-Receivers.tsx": {
    id: "routes/DB-Receivers";
    page: "/receiver";
  };
  "routes/DB-Gifters.tsx": {
    id: "routes/DB-Gifters";
    page: "/gifter";
  };
  "routes/Dashboard.tsx": {
    id: "routes/Dashboard";
    page: "/dashboard";
  };
  "routes/ChoiceRG.tsx": {
    id: "routes/ChoiceRG";
    page: "/choicerg";
  };
};