"""Add all energy tables

Revision ID: bcf20fd404a0
Revises: aeb7e819a068
Create Date: 2025-10-02 16:07:26.314803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf20fd404a0'
down_revision: Union[str, Sequence[str], None] = 'aeb7e819a068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_prices_id'), 'hourly_prices', ['id'], unique=False)
    op.create_index(op.f('ix_hourly_prices_timestamp'), 'hourly_prices', ['timestamp'], unique=False)
    op.create_table('solar_bedrijf_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('solar_bedrijf_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_bedrijf_records_id'), 'solar_bedrijf_records', ['id'], unique=False)
    op.create_index(op.f('ix_solar_bedrijf_records_timestamp'), 'solar_bedrijf_records', ['timestamp'], unique=False)
    op.create_table('wind_turbine_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wind_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_turbine_records_id'), 'wind_turbine_records', ['id'], unique=False)
    op.create_index(op.f('ix_wind_turbine_records_timestamp'), 'wind_turbine_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wind_turbine_records_timestamp'), table_name='wind_turbine_records')
    op.drop_index(op.f('ix_wind_turbine_records_id'), table_name='wind_turbine_records')
    op.drop_table('wind_turbine_records')
    op.drop_index(op.f('ix_solar_bedrijf_records_timestamp'), table_name='solar_bedrijf_records')
    op.drop_index(op.f('ix_solar_bedrijf_records_id'), table_name='solar_bedrijf_records')
    op.drop_table('solar_bedrijf_records')
    op.drop_index(op.f('ix_hourly_prices_timestamp'), table_name='hourly_prices')
    op.drop_index(op.f('ix_hourly_prices_id'), table_name='hourly_prices')
    op.drop_table('hourly_prices')
    # ### end Alembic commands ###
