// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../ChoiceRG.js") | typeof import("../Dashboard.js")

type Info = GetInfo<{
  file: "routes/ChoiceRG.tsx" | "routes/Dashboard.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "routes/ChoiceRG";
  module: typeof import("../ChoiceRG.js");
}, {
  id: "routes/Dashboard";
  module: typeof import("../Dashboard.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }, false>;

export namespace Route {
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];
  export type LoaderArgs = Annotations["LoaderArgs"];
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];
  export type ActionArgs = Annotations["ActionArgs"];
  export type ClientActionArgs = Annotations["ClientActionArgs"];
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];
  export type ComponentProps = Annotations["ComponentProps"];
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
}
